[package]
name = "audio-in-stream-rs"
version = "0.1.0"
authors = ["Israel Basurto"]
license = "AGPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal="0.11.0"
atty="0.2.14"
tiny_http="0.7.0"
